# Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Initialize saved images list
  ansible.builtin.set_fact:
    saved_images: []

- name: Include metadata vars
  ansible.builtin.include_vars: "{{ omnia_metadata_file }}"
  register: include_metadata
  no_log: true
  tags: always

- name: Create omnia container images directory
  ansible.builtin.file:
    path: "{{ images_directory_path }}"
    state: directory
    mode: "{{ read_write_mode }}"

- name: Fetch images list to save as tar
  ansible.builtin.include_tasks: fetch_images_list.yml
  when:
    - container_images is not defined

- name: Set fact for container_images
  ansible.builtin.set_fact:
    container_images: "{{ container_images | default(base_container_images) }}"

- name: Include image save logic
  ansible.builtin.include_tasks: save_image_as_tar.yml
  loop: "{{ container_images }}"
  loop_control:
    loop_var: image_name

- name: Show all save images
  ansible.builtin.debug:
    msg: "{{ saved_images }}"
  when: saved_images | length > 0