#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: mysqldb_deployment.yml
mysqldb_storage: 1Gi
mysqldb_pvc_name: mysqldb-storage-claim
mysqldb_k8s_name: mysqldb
mysqldb_name: "idrac_telemetrydb"
mysqldb_container_port1: 3306
mysqldb_container_port2: 33060
mysql_image: "docker.io/library/mysql:9.3.0"

# Usage: k8s_secrets.yml
mysqldb_secrets_name: mysqldb-credentials

# Usage: idrac_telemetry_deployment.yml
service_cluster_idrac_telemetry_dir_path: "/opt/omnia/service_cluster/telemetry/idrac_telemetry"
dir_permissions_755: "0755"
idrac_telemetry_github_repo: https://github.com/dell/iDRAC-Telemetry-Reference-Tools.git
reference_tools_stable_commit: "94e7621"
idrac_telemetry_reference_git_clone_path: "{{ service_cluster_idrac_telemetry_dir_path }}/iDRAC-Telemetry-Reference-Tools"
idrac_git_clone_error_msg: |
  Failed to clone iDRAC Telemetry GitHub repository from {{ idrac_telemetry_github_repo }}
  to {{ idrac_telemetry_reference_path }}.
  Failure: {{ clone_idrac_telemetry.stderr | default(clone_idrac_telemetry.msg, true) | default('Unknown error', true) }}
idrac_telemetry_scripting_repo: "https://github.com/dell/iDRAC-Telemetry-Scripting.git"
idrac_telemetry_scripting_stable_commit: "f6999f5"
idrac_telemetry_scripting_git_clone_path: "{{ service_cluster_idrac_telemetry_dir_path }}/iDRAC-Telemetry-Scripting"
idrac_script_git_clone_error_msg: |
  Failed to clone iDRAC Telemetry GitHub repository from {{ idrac_telemetry_scripting_repo }}
  to {{ idrac_telemetry_scripting_git_clone_path }}.
max_retries: 10
delay_count: 5
telemetry_namespace: "telemetry"
idrac_telemetry_k8s_name: idrac-telemetry
go_image: "docker.io/library/golang:1.24"
activemq_image: "docker.io/rmohr/activemq:5.15.9"
activemq_http_port_1: 8161
activemq_http_port_2: 61616
messagebus_http_port: 61613
configui_http_port: 8082

# Usage: prometheus_deployment.yml
prometheus_pvc_name: "prometheus-pvc"
prometheus_k8s_name: "prometheus"
prometheus_configmap_name: "prometheus-config"
prometheus_image: "docker.io/prom/prometheus:v3.4.1"
prometheus_container_port: 9090
statefulset_replicas: 1
prometheus_storage: 1Gi
storage_class_name: "nfs-client"
prometheus_service_port: 30090
