#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Check if iDRAC Telemtery Receiver container is running after deployment
  containers.podman.podman_container_info:
    name: "{{ idrac_telemetry_receiver_container_name }}"
  register: idrac_receiver_container_status
  failed_when: false

- name: Stop and Remove iDRAC Telemtery Receiver container
  when: idrac_receiver_container_status.containers | length != 0
  block:
    - name: Stop the iDRAC Telemtery Receiver container
      containers.podman.podman_container:
        name: "{{ idrac_telemetry_receiver_container_name }}"
        state: stopped
      failed_when: false

    - name: Remove iDRAC Telemtery Receiver container
      containers.podman.podman_container:
        name: "{{ idrac_telemetry_receiver_container_name }}"
        state: absent
        force_delete: true

    - name: Remove iDRAC Telemtery Receiver and Offline repo Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ idrac_telemetry_receiver_cleanup_directory }}"

  rescue:
    - name: Failure iDRAC Telemtery Receiver container removal
      ansible.builtin.fail:
        msg: "{{ idrac_telemetry_receiver_container_name }} {{ container_removal_failure_msg }}"
