# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Configure secrets for idrac telemetry variables
  when: idrac_telemetry_support
  block:
    - name: Create namespace using k8s module
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ telemetry_namespace }}"

    - name: Encode mysqldb username
      ansible.builtin.shell: |
        set -o pipefail
        echo -n "{{ hostvars['localhost']['mysqldb_user'] }}" | base64
      register: mysqldb_user_encoded
      changed_when: false
      no_log: true

    - name: Encode mysqldb password
      ansible.builtin.shell: |
        set -o pipefail
        echo -n "{{ hostvars['localhost']['mysqldb_password'] }}" | base64
      register: mysqldb_password_encoded
      changed_when: false
      no_log: true

    - name: Encode mysqldb password for root user
      ansible.builtin.shell: |
        set -o pipefail
        echo -n "{{ hostvars['localhost']['mysqldb_root_password'] }}" | base64
      register: mysqldb_root_password_encoded
      changed_when: false
      no_log: true

    - name: Apply Kubernetes Secret for MySQL using k8s module
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ mysqldb_secrets_name }}"
            namespace: "{{ telemetry_namespace }}"
          type: Opaque
          data:
            mysqldb_user: "{{ mysqldb_user_encoded.stdout }}"
            mysqldb_password: "{{ mysqldb_password_encoded.stdout }}"
            mysqldb_root_password: "{{ mysqldb_root_password_encoded.stdout }}"
